// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots
package gohtml

var base = `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    {{ template "bootstrap.css" . }}
    {{ template "css" . }}
    <title></title>
</head>

<body>
<div id="header">
    <div id="logo">
        <a href="/">restic</a>
    </div>
    <ul class="nav">
        <li>
            <a href="/snapshots">Snapshots</a>
        </li>
        <li class="dropdown">
            <a href="#">Dropdown</a>
            <div class="dropdown-content">
                <a href="#">Link 1</a>
                <a href="#">Link 2</a>
                <a href="#">Link 3</a>
            </div>
        </li>
    </ul>
</div>
<div id="content">
    {{ template "content" . }}
</div>
{{ template "jqueryjs" . }}
{{ template "bootstrapjs" . }}
{{ template "js" . }}
</body>
</html>
`
