// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-18 02:35:36.995822 +0300 +03 m=+0.000969648
package gohtml

var base = `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <style type="text/css">
        body{
            padding:0;
            margin: 0;
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        }
        #header {
            height: 47px;
            top: 0;
            width: 100%;
        }
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #5f5d5d;
        }
        #logo {
            float:left;
            background-color: #4CAF50;
            height: 100%;
        }
        #logo a {
            padding:13px;
            text-decoration: none;
            color: white;
            font-family: "PT Sans", Helvetica, Arial, sans-serif;
            font-weight:bold;
            line-height: 1.25;
            text-transform: uppercase;
            display: block;
        }
        li {
            float: left;
            border-right: 1px solid #bbb;
        }

        li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover {
            background-color: #111;
        }

        .active {
            background-color: #111;
        }

        li:last-child {
            border-right: none;
        }
        #content {
            margin: 10px;
        }
        table {
            border-collapse: collapse;
            width: 100%;
        }
        table td, table th {
            border: 1px solid #ddd;
            padding: 8px;
        }
        table tr:nth-child(even){background-color: #f2f2f2;}
        table tr:hover {background-color: #ddd;}
        table th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #4CAF50;
            color: white;
        }
    </style>
    <title></title>
</head>

<body>
<div id="header">
    <div id="logo">
        <a href="/">restic</a>
    </div>
    <ul class="nav">
        <li>
            <a href="/snapshots">Snapshots</a>
        </li>
    </ul>
</div>
<div id="content">
    {{ template "content" . }}
</div>
</body>
</html>
`
