// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots
package gohtml

var dirtree = `<li>
    {{ if .Node.IsDir }}
        <input type="checkbox"/>
        <span>{{ .Node.Name }}</span>
    {{ else }}
        <span><a href="/dump?id={{.Data.Params.id}}&path={{ .Node.Path }}&size={{ .Node.Size }}">{{ .Node.Name }}</a></span>
    {{ end }}
    {{ if .Node.IsDir }}
        <ul>
            {{ .Node.Nodes.Render .Data }}
        </ul>
    {{ end }}
</li>
`
