// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
package gohtml

var dirtree = `<li>
    {{ if .Node.IsDir }}
        <input type="checkbox"/>
    {{ end }}
    <span>{{ .Node.Name }}</span>
    {{ if .Node.IsDir }}
        <ul>
            {{ .Node.Nodes.Render }}
        </ul>
    {{ end }}
</li>
`
