// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots
package gohtml

var error = `{{define "content"}}
    <div id="notfound">
        <div class="notfound">
            <h2>{{ .Status }} - {{ .Title }}</h2>
            <p>{{ .Err }}</p>
        </div>
    </div>
{{end}}
`
