// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-18 23:35:45.125546 +0300 +03 m=+0.003793249
package gohtml

var error = `{{define "content"}}
    <div id="notfound">
        <div class="notfound">
            <h2>{{ .Status }} - {{ .Title }}</h2>
            <p>{{ .Err }}</p>
        </div>
    </div>
{{end}}
`
