// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-18 02:35:36.996426 +0300 +03 m=+0.001573786
package gohtml

var index = `{{define "content"}}
    <p class="red">Home page</p>
{{end}}
`
