// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots
package gohtml

var index = `{{define "content"}}
    <h1 class="display-4">This is a http port for restic cli commands</h1>
{{end}}
`
