// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-18 23:35:45.126146 +0300 +03 m=+0.004392592
package gohtml

var index = `{{define "content"}}
    <p class="red">Home page</p>
{{end}}
`
