// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots
package gohtml

var js = `{{define "js"}}
<script type="application/javascript">
    $(function () {
        alert("111");
    });
</script>
{{end}}
`
