// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
package gohtml

var ls = `{{define "content"}}
    <h1>Snapshot contents {{.SnapshotID}}</h1>

    <div class="mt-2">
        <form method="get">
            <div class="col-50 mt-10">
                <input type="hidden" value="{{ .Params.id }}" name="id">
                <label>
                    Long
                    <input type="checkbox" name="long" {{if .Params.long }} checked="checked" {{end}}>
                </label>
                <label>
                    Recursive
                    <input type="checkbox" name="recursive" {{if .Params.recursive }} checked="checked" {{end}}>
                </label>
                <div class="mt-10">
                    <label for="path">Path</label>
                    <input type="text" id="tag" name="path" placeholder="path"
                           value="{{if .Params.path }}{{.Params.path}}{{end}}">
                </div>
            </div>
            <div class="clear"></div>
            <div class="mt-10">
                <a href="/snapshots" class="button mr-5">Reset</a>
                <input type="submit" value="Submit" class="button">
            </div>
        </form>
    </div>
    <div class="clear"></div>
    <div class="dirs mt-10">
        <ul id="tree">
            {{  .DirTree.Render . }}
        </ul>
    </div>
{{end}}
`
