// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots
package gohtml

var ls = `{{define "content"}}
    <h1 class="display-4">Snapshot contents {{.SnapshotID}}</h1>
    <form class="row" method="get">
        <div class="col-4">
            <input type="hidden" value="{{ .Params.id }}" name="id">
            <div class="form-group mb-1">
                <label for="path" class="m-0">Path</label>
                <input class="form-control form-control-sm" type="text" id="path" name="path"
                       value="{{if .Params.path }}{{.Params.path}}{{end}}">
                <small id="pathHelp" class="form-text text-muted">
                    For multiple use comma separated values
                </small>
            </div>
            <div class="form-group mb-1">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="/snapshots" class="btn btn-primary mr-1">Reset</a>
            </div>
        </div>
        <div class="col-4">
            <div class="form-check mb-1">
                <input class="form-check-input" type="checkbox" id="long"
                       name="long" {{if .Params.long }} checked="checked" {{end}}>
                <label class="form-check-label" for="long">
                    Long
                </label>
            </div>
            <div class="form-check mb-1">
                <input class="form-check-input" type="checkbox" id="recursive"
                       name="recursive" {{if .Params.recursive }} checked="checked" {{end}}>
                <label class="form-check-label" for="long">
                    Recursive
                </label>
            </div>
        </div>
    </form>
    <div class="row mt-4">
        <div class="col-md-12">
            <ol class="tree">
                {{  .DirTree.Render . }}
            </ol>
        </div>
    </div>
{{end}}
`
