// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-18 02:35:36.996829 +0300 +03 m=+0.001977392
package gohtml

var snapshots = `{{define "content"}}
    <h1>Snapshots</h1>
    <table id="customers">
        <tr>
            <th>ID</th>
            <th>Time</th>
            <th>Host</th>
            <th>Tags</th>
            <th>Paths</th>
        </tr>
        {{range $snapshot := .Snapshots}}
            <tr>
                <td>{{$snapshot.ShortID}}</td>
                <td>{{$snapshot.Snapshot.Time.Format "2006-01-02 15:04:05"}}</td>
                <td>{{$snapshot.Snapshot.Hostname}}</td>
                <td>
                    {{if $snapshot.Snapshot.Tags }}
                        {{ joinStrings $snapshot.Snapshot.Tags "," }}
                    {{end}}
                </td>
                <td>
                    {{if $snapshot.Snapshot.Paths }}
                        {{range $path := $snapshot.Snapshot.Paths}}
                            {{ $path }} <br>
                        {{end}}
                    {{end}}
                </td>
            </tr>
        {{end}}
    </table>
{{end}}
`
