// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-18 02:35:36.997175 +0300 +03 m=+0.002323545
package gohtml

var TemplatesMap = map[string]string{
	"base":      base,
	"index":     index,
	"snapshots": snapshots,
}
