// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-18 23:35:45.128172 +0300 +03 m=+0.006419127
package gohtml

var TemplatesMap = map[string]string{
	"base":      base,
	"error":     error,
	"index":     index,
	"ls":        ls,
	"snapshots": snapshots,
}
