// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
package gohtml

var TemplatesMap = map[string]string{
	"base":      base,
	"css":       css,
	"error":     error,
	"index":     index,
	"ls":        ls,
	"snapshots": snapshots,
}
